#! /bin/bash

set -eu

if ! [[ $PACKAGE_BUCKET ]]; then
    echo "PACKAGE_BUCKET env var must be set"
    exit 1
fi

template_file=$(mktemp)
aws cloudformation package --template-file backend/template.yml \
  --s3-bucket $PACKAGE_BUCKET > $template_file
aws cloudformation deploy --template-file $template_file \
  --stack-name ${STACK_NAME-AppSyncRelay} --capabilities CAPABILITY_NAMED_IAM
