#!/bin/bash

set -eu

jq_prog='.Stacks[0].Outputs | map({key: .OutputKey, value: .OutputValue}) | from_entries'
echo "Fetching config for CloudFormation stack..."
export APPSYNC_CONFIG="$(aws cloudformation describe-stacks --stack-name ${STACK_NAME-AppSyncRelay} | jq "$jq_prog")"

"$@"
