#!/bin/bash

# Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

set -eu

jq_prog='.Stacks[0].Outputs | map({key: .OutputKey, value: .OutputValue}) | from_entries'
echo "Fetching config for CloudFormation stack..."
export APPSYNC_CONFIG="$(aws cloudformation describe-stacks --stack-name ${STACK_NAME-AppSyncRelay} | jq "$jq_prog")"

"$@"
